Update suppressions.xml syntax
Observed that downstream dependencies threw the following
error when ingesting the prior checkstyle config files:

CheckstyleException: Unable to parse https://raw.githubusercontent.com/Consent-Management-Platform/checkstyle-config/main/src/main/resources/suppressions.xml - The end-tag for element type "suppress" must end with a '>' delimiter.

Updated suppressions.xml syntax to add explicit closing
" />" delimiters instead of just ">" to see if this
resolves the issue, and incrementing the package bug fix
version.